# ! PIPELINE DE CI
name: Test
#* cuando hagamos push se ejecutara el pipeline
on: [push]

jobs:
  build:
    #* se ejecutara en ubuntu
    runs-on: ubuntu-latest
    #* se ejecutara en el directorio de la app
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        pytest
