export const departamentos = [
  "Alta Verapaz",
  "Baja Verapaz",
  "Chimaltenango",
  "Chiquimula",
  "El Progreso",
  "Escuintla",
  "Guatemala",
  "Huehuetenango",
  "Izabal",
  "Jalapa",
  "Jutiapa",
  "Peten",
  "Quetzaltenango",
  "Quiche",
  "Retalhuleu",
  "Sacatepequez",
  "San Marcos",
  "Santa Rosa",
  "Solola",
  "Suchitepequez",
  "Totonicapan",
  "Zacapa",
];

export const municipios = {
  "Alta Verapaz": [
    "Cobán",
    "Chisec",
    "San Juan Chamelco",
    "San Pedro Carchá",
    "San Cristóbal Verapaz",
    "Santa Cruz Verapaz",
    "Tactic",
    "Tamahú",
    "Tucurú",
    "Senahú",
    "Santa María Cahabón",
    "Chahal",
    "Fray Bartolomé de las Casas",
    "Santa Catarina La Tinta",
    "Raxruhá",
    "Chisec",
  ],
  "Baja Verapaz": [
    "Salamá",
    "San Miguel Chicaj",
    "Rabinal",
    "Cubulco",
    "Granados",
    "Purulhá",
    "San Jerónimo",
  ],
  "Chimaltenango": [
    "Chimaltenango",
    "San José Poaquil",
    "San Martín Jilotepeque",
    "San Juan Comalapa",
    "Santa Apolonia",
    "Tecpán Guatemala",
    "Patzún",
    "Pochuta",
    "Comalapa",
    "Santa Cruz Balanyá",
    "Acatenango",
    "Yepocapa",
    "San Andrés Itzapa",
    "Parramos",
    "Zaragoza",
    "El Tejar",
  ],
  "Chiquimula": [
    "Chiquimula",
    "San José La Arada",
    "San Juan Ermita",
    "Jocotán",
    "Camotán",
    "Olopa",
    "Esquipulas",
    "Concepción Las Minas",
    "Quezaltepeque",
    "San Jacinto",
  ],
  "El Progreso": [
    "Guastatoya",
    "Morazán",
    "San Agustín Acasaguastlán",
    "San Antonio La Paz",
    "San Cristóbal Acasaguastlán",
    "El Jícaro",
    "Sansare",
  ],
  "Escuintla": [
    "Escuintla",
    "Santa Lucía Cotzumalguapa",
    "La Democracia",
    "Siquinalá",
    "Masagua",
    "Tiquisate",
    "La Gomera",
    "Guamuchal",
    "Iztapa",
    "Palín",
    "San Vicente Pacaya",
    "Nueva Concepción",
  ],
  "Guatemala": [
    "Ciudad de Guatemala",
    "Santa Catarina Pinula",
    "San José Pinula",
    "San José del Golfo",
    "Palencia",
    "Chinautla",
    "San Pedro Ayampuc",
    "Mixco",
    "San Pedro Sacatepéquez",
    "San Juan Sacatepéquez",
    "San Raymundo",
    "Chuarrancho",
    "Fraijanes",
    "Amatitlán",
    "Villa Nueva",
    "Villa Canales",
    "Petapa",
  ],
  "Huehuetenango": [
    "Huehuetenango",
    "Chiantla",
    "Malacatancito",
    "Cuilco",
    "Nentón",
    "San Pedro Necta",
    "Jacaltenango",
    "San Pedro Soloma",
    "San Ildefonso Ixtahuacán",
    "Santa Bárbara",
    "La Libertad",
    "La Democracia",
    "San Miguel Acatán",
    "San Rafael La Independencia",
    "Todos Santos Cuchumatán",
    "San Juan Atitán",
    "Santa Eulalia",
    "San Mateo Ixtatán",
    "Colotenango",
  ],
  "Izabal": ["Puerto Barrios", "Livingston", "El Estor", "Morales", "Los Amates"],
  "Jalapa": [
    "Jalapa",
    "San Pedro Pinula",
    "San Luis Jilotepeque",
    "San Manuel Chaparrón",
    "San Carlos Alzatate",
    "Monjas",
    "Mataquescuintla",
  ],
  "Jutiapa": [
    "Agua Blanca",
    "Asunción Mita",
    "Atescatempa",
    "Comapa",
    "Conguaco",
    "El Adelanto",
    "El Progreso",
    "Jalpatagua",
    "Jerez",
    "Jutiapa",
    "Moyuta",
    "Pasaco",
    "Quezada",
    "San José Acatempa",
    "Santa Catarina Mita",
    "Yupiltepeque",
    "Zapotitlán",
  ],
  "Peten": [
    "Flores",
    "San Benito",
    "San Andrés",
    "La Libertad",
    "San Francisco",
    "Santa Ana",
    "Dolores",
    "San Luis",
    "Sayaxché",
    "Melchor de Mencos",
    "Poptún",
    "Las Cruces",
    "El Chal",
    "Ixcán",
    "Santa Cruz",
    "San José",
    "San Fernando",
  ],
  "Quetzaltenango": [
    "Almolonga",
    "Cabricán",
    "Cajolá",
    "Cantel",
    "Coatepeque",
    "Colomba",
    "Concepción Chiquirichapa",
    "El Palmar",
    "Flores Costa Cuca",
    "Génova",
    "Huitán",
    "La Esperanza",
    "Olintepeque",
    "Palestina de los Altos",
    "Quetzaltenango",
    "Salcajá",
    "San Carlos Sija",
    "San Francisco La Unión",
    "San Juan Ostuncalco",
    "San Martín Sacatepéquez",
    "San Mateo",
    "San Miguel Siguilá",
    "Sibilia",
    "Zunil",
  ],
  "Quiche": [
    "Santa Cruz del Quiché",
    "Chiché",
    "Chinique",
    "Zacualpa",
    "Chajul",
    "Chichicastenango",
    "Patzité",
    "San Antonio Ilotenango",
    "San Bartolomé Jocotenango",
    "San Juan Cotzal",
    "Joyabaj",
    "Nebaj",
    "San Andrés Sajcabajá",
    "Uspantán",
    "Sacapulas",
    "San Pedro Jocopilas",
    "Cunén",
    "San Juan Ixcoy",
    "San Mateo Ixtatán",
    "Santa María Nebaj",
    "Aguacatán",
    "Canillá",
    "Chicamán",
    "Ixcán",
    "Pachalum",
  ],
  "Retalhuleu": [
    "Retalhuleu",
    "Champerico",
    "San Sebastián",
    "Santa Cruz Muluá",
    "San Martín Zapotitlán",
    "San Felipe",
    "San Andrés Villa Seca",
    "Nuevo San Carlos",
    "El Asintal",
  ],
  "Sacatepequez": [
    "Antigua Guatemala",
    "Jocotenango",
    "Pastores",
    "Sumpango",
    "Santo Domingo Xenacoj",
    "Santa María de Jesús",
    "Ciudad Vieja",
    "San Bartolomé Milpas Altas",
    "San Lucas Sacatepéquez",
    "Magdalena Milpas Altas",
    "Santa Lucía Milpas Altas",
    "San Juan Alotenango",
  ],
  "San Marcos": [
    "San Marcos",
    "San Pedro Sacatepéquez",
    "San Antonio Sacatepéquez",
    "Comitancillo",
    "San Miguel Ixtahuacán",
    "Concepción Tutuapa",
    "Tacaná",
    "Sibinal",
    "Tajumulco",
    "Tejutla",
    "San Rafael Pie de La Cuesta",
    "Nuevo Progreso",
    "El Tumbador",
    "Malacatán",
    "Catarina",
    "Ayutla",
    "Ocós",
    "Pajapita",
    "Ixchiguán",
    "Sipacapa",
    "Esquipulas Palo Gordo",
  ],
  "Santa Rosa": [
    "Cuilapa",
    "Barberena",
    "Casillas",
    "Santa Rosa de Lima",
    "Oratorio",
    "San Juan Tecuaco",
    "Nueva Santa Rosa",
    "Guazacapán",
    "Chiquimulilla",
    "Taxisco",
    "Santa María Ixhuatán",
    "Pueblo Nuevo Viñas",
  ],
  "Solola": [
    "Sololá",
    "San José Chacayá",
    "Santa María Visitación",
    "Santa Lucía Utatlán",
    "Nahualá",
    "Santa Catarina Ixtahuacán",
    "Santa Clara La Laguna",
    "Concepción",
    "San Andrés Semetabaj",
    "Panajachel",
    "Santa Catarina Palopó",
    "San Antonio Palopó",
    "San Lucas Tolimán",
    "Santa Cruz La Laguna",
    "San Pablo La Laguna",
    "San Juan La Laguna",
    "San Marcos La Laguna",
  ],
  "Suchitepequez": [
    "Mazatenango",
    "Cuyotenango",
    "San Francisco Zapotitlán",
    "San Bernardino",
    "San José El Idolo",
    "Santo Domingo Suchitepequez",
    "San Lorenzo",
    "Samayac",
    "San Pablo Jocopilas",
    "San Antonio Suchitepéquez",
    "San Miguel Panán",
    "San Gabriel",
    "Chicacao",
    "Patulul",
    "Santa Bárbara",
    "San Juan Bautista",
    "Santo Tomás La Unión",
    "Zunilito",
  ],
  "Totonicapan": [
    "Totonicapán",
    "San Cristóbal Totonicapán",
    "San Francisco El Alto",
    "San Andrés Xecul",
    "Momostenango",
    "Santa María Chiquimula",
    "Santa Lucía La Reforma",
    "San Bartolo",
    "San Antonio Sija",
    "San Miguelito",
  ],
  "Zacapa": [
    "Zacapa",
    "Estanzuela",
    "Río Hondo",
    "Gualán",
    "Teculután",
    "Usumatlán",
    "Cabañas",
    "San Diego",
    "La Unión",
  ],
  "": []
};
